server:
    port: ${port:8081}
    context-path: #/liuzh/
logging:
    level:
        tk.mybatis: DEBUG
    file: log.log
spring:
  profiles:
    active: ${active:dev}
debug: true
---

spring:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
    profiles: dev
    mvc:
      view:
          prefix: /templates/
          suffix: .ftl
      freemarker:
          cache: false
          request-context-attribute: request
druid:
    datasource:
        name: test
        url: jdbc:mysql://192.168.99.100:3306/test
        username: root
        password: admin

---