server:
    port: ${port:80}
    context-path: /t
logging:
    file: D:/log/spring.log
#        tk.mybatis: DEBUG
spring:
  profiles:
    active: ${active:dev}
#debug: true
---

spring:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
    profiles: dev
    mvc:
      view:
          prefix: /templates/
          suffix: .ftl
      freemarker:
          cache: false
          request-context-attribute: request
    rabbitmq:
      host: 192.168.99.100
      port: 5672
      username: nsc
      password: newtouch
druid:
    datasource:
        name: test
        url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: admin

---